openapi: '3.0.0'
info:
  title: Savings API
  version: '1.0.0'
servers:
  - url: https://savings-api.example
paths:
  /savings-records:
    get:
      description: >
        Endpoint to retrieve resident's savings record
      operationId: getResidentSavingsRecords
      parameters:
        - in: query
          name: page
          required: false
          schema:
            type: integer
            description: >
              Page number to query records from. Default value is 1 if not specified.
        - in: query
          name: size
          required: false
          schema:
            type: integer
            description: >
              Page size. Default value is 10 if not specified.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSavingsRecordsSuccessResponse'
              x-examples-mapping: './docs/savings-api/examples/mappings.yaml'
              examples:
                hasSavingRecords:
                  # summary: Savings Records Available
                  # value:
                  #   {
                  #     "data": [
                  #       {
                  #         "created_on": "2023-01-01T00:00:00.000Z",
                  #         "record_type": "salary",
                  #         "amount": 1000.12
                  #       },
                  #       {
                  #         "created_on": "2023-02-01T00:00:00.000Z",
                  #         "record_type": "self",
                  #         "amount": 750.00
                  #       },
                  #       {
                  #         "created_on": "2023-02-05T00:00:00.000Z",
                  #         "record_type": "offset",
                  #         "amount": 500.00
                  #       }
                  #     ]
                  #   }
                  externalValue: './docs/savings-api/examples/get-savings-records-success-response.json'

components:
  schemas:
    GetSavingsRecordsSuccessResponse:
      type: object
      require:
        - data
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Savings'
    Savings:
      type: object
      properties:
        created_on:
          type: string
          pattern: ^20(1[0-9]|2[1-3])-(0[1-9]|1[1-2])-(0[1-9]|[1-2][0-9]|30)T([0-1][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]Z$
          description: |
            Date/time when record was created
        record_type:
          type: string
          enum:
            - salary
            - self
            - offset
          description: |
            Types of savings record_type:
              * `salary` - Savings from salary
              * `self` - Self contribution
              * `offset` - Financial offset packages
        amount:
          type: number
          pattern: ^[0-9]*\.[0-9]{2}$
          description: |
            Should be float number up to 2 decimal places

        